[project]
name = "etf-watchdog"
version = "0.1.0"
description = "Personal ETF tracker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alpaca-py>=0.42.1",
    "fastapi[standard]>=0.116.1",
    "pydantic[email]>=2.11.7",
]
